// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6UIZQ-B-Qmwbepb2CYboFJb4Qp83L8q0',
    appId: '1:1568008705:android:1caf4baba544ddad15ae00',
    messagingSenderId: '1568008705',
    projectId: 'give-app-d9a07',
    storageBucket: 'give-app-d9a07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlrMy7rD7-2QJAHTjvLfBvAOV0VikUPH8',
    appId: '1:1568008705:ios:465450f6f58fb97315ae00',
    messagingSenderId: '1568008705',
    projectId: 'give-app-d9a07',
    storageBucket: 'give-app-d9a07.firebasestorage.app',
    iosBundleId: 'com.example.giveApp',
  );
}
