// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZif_zhmOkQMTo_7D3QyI41oG5A5nzW0',
    appId: '1:1044465475449:web:5caa9ab054d0504abb59a8',
    messagingSenderId: '1044465475449',
    projectId: 'give-app-25119',
    authDomain: 'give-app-25119.firebaseapp.com',
    storageBucket: 'give-app-25119.firebasestorage.app',
    measurementId: 'G-8GX4BBRW5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCER9Uf0qplFvC1ZjYUrol838OlH3nn7gw',
    appId: '1:1044465475449:android:2a2bb8648f8efd9fbb59a8',
    messagingSenderId: '1044465475449',
    projectId: 'give-app-25119',
    storageBucket: 'give-app-25119.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArHP23vKoC6Bwl-M80OFhmvyJPl4GzVR8',
    appId: '1:1044465475449:ios:67744a8609192b16bb59a8',
    messagingSenderId: '1044465475449',
    projectId: 'give-app-25119',
    storageBucket: 'give-app-25119.firebasestorage.app',
    iosBundleId: 'com.example.giveApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArHP23vKoC6Bwl-M80OFhmvyJPl4GzVR8',
    appId: '1:1044465475449:ios:67744a8609192b16bb59a8',
    messagingSenderId: '1044465475449',
    projectId: 'give-app-25119',
    storageBucket: 'give-app-25119.firebasestorage.app',
    iosBundleId: 'com.example.giveApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLZif_zhmOkQMTo_7D3QyI41oG5A5nzW0',
    appId: '1:1044465475449:web:36818821d1161df0bb59a8',
    messagingSenderId: '1044465475449',
    projectId: 'give-app-25119',
    authDomain: 'give-app-25119.firebaseapp.com',
    storageBucket: 'give-app-25119.firebasestorage.app',
    measurementId: 'G-0HZLZ76NDX',
  );
}
